# Generated by Django 4.2.2 on 2023-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_documentation', '0002_remove_hiddenimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenimage',
            name='encrypted_image_path',
        ),
        migrations.AddField(
            model_name='hiddenimage',
            name='encrypted_image',
            field=models.ImageField(default='default_image.jpg', upload_to='hidden_images/encrypted/'),
        ),
    ]
