# Generated by Django 4.2.2 on 2023-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_documentation', '0003_remove_hiddenimage_encrypted_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenimage',
            name='encrypted_image',
        ),
        migrations.AddField(
            model_name='hiddenimage',
            name='encrypted_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
